version: 0.2
phases:
  pre_build:
    commands:
      - echo Restore started on `date`
      - pip install --upgrade awscli
      - dotnet restore PipelineCoreApp/PipelineCoreApp.csproj
  build:
    commands:
      - echo Build started on `date`
      - dotnet publish -c release -o ./build_output PipelineCoreApp/PipelineCoreApp.csproj
artifacts:
  files:
    - PipelineCoreApp/build_output/**/*
    - scripts/**/*
    - appspec.yml
